
//User
export const RECEIVE_LOGGED_USER = "RECEIVE_LOGGED_USER"
export const USER_LOGOUT = " USER_LOGOUT"
export const RECEIVE_CONSULTANTS = "RECEIVE_CONSULTANTS"

//Products
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_CURRENT_PRODUCT = "RECEIVE_CURRENT_PRODUCT";
export const RECEIVE_PRODUCT_PARAMETERS = "RECEIVE_PRODUCT_PARAMETERS";
export const RECEIVE_VIEW_PRODUCT_CHANGE = "RECEIVE_VIEW_PRODUCT_CHANGE";
export const RESET_ORDER_PRODUCTS = "RESET_ORDER_PRODUCTS";

//Order
export const ADD_PRODUCT_TO_ORDER = "ADD_PRODUCT_TO_ORDER";
export const RECEIVE_ORDERS = "RECEIVE_ORDERS"
export const ADD_PRODUCT_FROM_ORDER = "ADD_PRODUCT_FROM_ORDER";
export const REMOVE_PRODUCT_FROM_ORDER = "REMOVE_PRODUCT_FROM_ORDER";
export const DECREMENT_PRODUCT_FROM_ORDER = "DECREMENT_PRODUCT_FROM_ORDER";
export const REMOVE_ORDER = "REMOVE_ORDER";
export const RECEIVE_PRODUCT_PATH_CHANGE = "RECEIVE_PRODUCT_PATH_CHANGE";



  
  