
//User
export const RECEIVE_LOGGED_USER = "RECEIVE_LOGGED_USER"
export const USER_LOGOUT = " USER_LOGOUT"


//Products
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_CURRENT_PRODUCT = "RECEIVE_CURRENT_PRODUCT";
export const RECEIVE_PRODUCT_PARAMETERS = "RECEIVE_PRODUCT_PARAMETERS";
export const RECEIVE_PRODUCT_BY_LEGACY = "RECEIVE_PRODUCT_BY_LEGACY";
  

//Magazines
export const RECEIVE_MAGAZINES = "RECEIVE_MAGAZINES";
export const RECEIVE_CURRENT_MAGAZINE = "RECEIVE_CURRENT_MAGAZINE";
export const RECEIVE_MAGAZINE_ERRORS = "RECEIVE_MAGAZINE_ERRORS";
export const RECEIVE_MAGAZINE_PUBLICATIONS = "RECEIVE_MAGAZINE_PUBLICATIONS";
export const RECEIVE_MAGAZINE_PAGES = "RECEIVE_MAGAZINE_PAGES";



  
  